export const usersUnsorted = [
  {
    id: '0F8JIqi4zwvb77FGz6Wt',
    email: 'heinz-georg.fiedler@example.com',
    firstName: 'Heinz-Georg',
    lastName: 'Fiedler',
    picture: 'https://randomuser.me/api/portraits/men/81.jpg',
    title: 'mr',
  },
  {
    id: '0P6E1d4nr0L1ntW8cjGU',
    email: 'katie.hughes@example.com',
    firstName: 'Katie',
    lastName: 'Hughes',
    picture: 'https://randomuser.me/api/portraits/women/74.jpg',
    title: 'miss',
  },
  {
    id: '1Lkk06cOUCkiAsUXFLMN',
    email: 'vetle.aasland@example.com',
    firstName: 'Vetle',
    lastName: 'Aasland',
    picture: 'https://randomuser.me/api/portraits/men/97.jpg',
    title: 'mr',
  },
  {
    id: '1OuR3CWOEsfISTpFxsG7',
    email: 'dylan.vasquez@example.com',
    firstName: 'Dylan',
    lastName: 'Vasquez',
    picture: 'https://randomuser.me/api/portraits/men/66.jpg',
    title: 'mr',
  },
  {
    id: '1pRsh5nXDIH3pjEOZ17A',
    email: 'margarita.vicente@example.com',
    firstName: 'Margarita',
    lastName: 'Vicente',
    picture: 'https://randomuser.me/api/portraits/women/5.jpg',
    title: 'miss',
  },
  {
    id: '3JAf8R85oIlxXd58Piqk',
    email: 'joey.oliver@example.com',
    firstName: 'Joey',
    lastName: 'Oliver',
    picture: 'https://randomuser.me/api/portraits/men/61.jpg',
    title: 'mr',
  },
  {
    id: '5aZRSdkcBOM6j3lkWEoP',
    email: 'lilja.lampinen@example.com',
    firstName: 'Lilja',
    lastName: 'Lampinen',
    picture: 'https://randomuser.me/api/portraits/women/50.jpg',
    title: 'ms',
  },
  {
    id: '5tVxgsqPCjv2Ul5Rc7gw',
    email: 'abigail.liu@example.com',
    firstName: 'Abigail',
    lastName: 'Liu',
    picture: 'https://randomuser.me/api/portraits/women/83.jpg',
    title: 'miss',
  },
  {
    id: '6wy6UNkZueJfIUfq88d5',
    email: 'melanie.pilz@example.com',
    firstName: 'Melanie',
    lastName: 'Pilz',
    picture: 'https://randomuser.me/api/portraits/women/32.jpg',
    title: 'miss',
  },
  {
    id: '7DbXNPWlNDR4QYVvFZjr',
    email: 'evan.carlson@example.com',
    firstName: 'Evan',
    lastName: 'Carlson',
    picture: 'https://randomuser.me/api/portraits/men/80.jpg',
    title: 'mr',
  },
];

export const usersSortedByFirstNameAsc = [
  {
    id: '5tVxgsqPCjv2Ul5Rc7gw',
    email: 'abigail.liu@example.com',
    firstName: 'Abigail',
    lastName: 'Liu',
    picture: 'https://randomuser.me/api/portraits/women/83.jpg',
    title: 'miss',
  },
  {
    id: '1OuR3CWOEsfISTpFxsG7',
    email: 'dylan.vasquez@example.com',
    firstName: 'Dylan',
    lastName: 'Vasquez',
    picture: 'https://randomuser.me/api/portraits/men/66.jpg',
    title: 'mr',
  },
  {
    id: '7DbXNPWlNDR4QYVvFZjr',
    email: 'evan.carlson@example.com',
    firstName: 'Evan',
    lastName: 'Carlson',
    picture: 'https://randomuser.me/api/portraits/men/80.jpg',
    title: 'mr',
  },
  {
    id: '0F8JIqi4zwvb77FGz6Wt',
    email: 'heinz-georg.fiedler@example.com',
    firstName: 'Heinz-Georg',
    lastName: 'Fiedler',
    picture: 'https://randomuser.me/api/portraits/men/81.jpg',
    title: 'mr',
  },
  {
    id: '3JAf8R85oIlxXd58Piqk',
    email: 'joey.oliver@example.com',
    firstName: 'Joey',
    lastName: 'Oliver',
    picture: 'https://randomuser.me/api/portraits/men/61.jpg',
    title: 'mr',
  },
  {
    id: '0P6E1d4nr0L1ntW8cjGU',
    email: 'katie.hughes@example.com',
    firstName: 'Katie',
    lastName: 'Hughes',
    picture: 'https://randomuser.me/api/portraits/women/74.jpg',
    title: 'miss',
  },
  {
    id: '5aZRSdkcBOM6j3lkWEoP',
    email: 'lilja.lampinen@example.com',
    firstName: 'Lilja',
    lastName: 'Lampinen',
    picture: 'https://randomuser.me/api/portraits/women/50.jpg',
    title: 'ms',
  },
  {
    id: '1pRsh5nXDIH3pjEOZ17A',
    email: 'margarita.vicente@example.com',
    firstName: 'Margarita',
    lastName: 'Vicente',
    picture: 'https://randomuser.me/api/portraits/women/5.jpg',
    title: 'miss',
  },
  {
    id: '6wy6UNkZueJfIUfq88d5',
    email: 'melanie.pilz@example.com',
    firstName: 'Melanie',
    lastName: 'Pilz',
    picture: 'https://randomuser.me/api/portraits/women/32.jpg',
    title: 'miss',
  },
  {
    id: '1Lkk06cOUCkiAsUXFLMN',
    email: 'vetle.aasland@example.com',
    firstName: 'Vetle',
    lastName: 'Aasland',
    picture: 'https://randomuser.me/api/portraits/men/97.jpg',
    title: 'mr',
  },
];

export const usersSortedByFirstNameDesc = [
  {
    id: '5tVxgsqPCjv2Ul5Rc7gw',
    email: 'abigail.liu@example.com',
    firstName: 'Abigail',
    lastName: 'Liu',
    picture: 'https://randomuser.me/api/portraits/women/83.jpg',
    title: 'miss',
  },
  {
    id: '1OuR3CWOEsfISTpFxsG7',
    email: 'dylan.vasquez@example.com',
    firstName: 'Dylan',
    lastName: 'Vasquez',
    picture: 'https://randomuser.me/api/portraits/men/66.jpg',
    title: 'mr',
  },
  {
    id: '7DbXNPWlNDR4QYVvFZjr',
    email: 'evan.carlson@example.com',
    firstName: 'Evan',
    lastName: 'Carlson',
    picture: 'https://randomuser.me/api/portraits/men/80.jpg',
    title: 'mr',
  },
  {
    id: '0F8JIqi4zwvb77FGz6Wt',
    email: 'heinz-georg.fiedler@example.com',
    firstName: 'Heinz-Georg',
    lastName: 'Fiedler',
    picture: 'https://randomuser.me/api/portraits/men/81.jpg',
    title: 'mr',
  },
  {
    id: '3JAf8R85oIlxXd58Piqk',
    email: 'joey.oliver@example.com',
    firstName: 'Joey',
    lastName: 'Oliver',
    picture: 'https://randomuser.me/api/portraits/men/61.jpg',
    title: 'mr',
  },
  {
    id: '0P6E1d4nr0L1ntW8cjGU',
    email: 'katie.hughes@example.com',
    firstName: 'Katie',
    lastName: 'Hughes',
    picture: 'https://randomuser.me/api/portraits/women/74.jpg',
    title: 'miss',
  },
  {
    id: '5aZRSdkcBOM6j3lkWEoP',
    email: 'lilja.lampinen@example.com',
    firstName: 'Lilja',
    lastName: 'Lampinen',
    picture: 'https://randomuser.me/api/portraits/women/50.jpg',
    title: 'ms',
  },
  {
    id: '1pRsh5nXDIH3pjEOZ17A',
    email: 'margarita.vicente@example.com',
    firstName: 'Margarita',
    lastName: 'Vicente',
    picture: 'https://randomuser.me/api/portraits/women/5.jpg',
    title: 'miss',
  },
  {
    id: '6wy6UNkZueJfIUfq88d5',
    email: 'melanie.pilz@example.com',
    firstName: 'Melanie',
    lastName: 'Pilz',
    picture: 'https://randomuser.me/api/portraits/women/32.jpg',
    title: 'miss',
  },
  {
    id: '1Lkk06cOUCkiAsUXFLMN',
    email: 'vetle.aasland@example.com',
    firstName: 'Vetle',
    lastName: 'Aasland',
    picture: 'https://randomuser.me/api/portraits/men/97.jpg',
    title: 'mr',
  },
];

export const usersSortedByLastNameAsc = [
  {
    id: '1Lkk06cOUCkiAsUXFLMN',
    email: 'vetle.aasland@example.com',
    firstName: 'Vetle',
    lastName: 'Aasland',
    picture: 'https://randomuser.me/api/portraits/men/97.jpg',
    title: 'mr',
  },
  {
    id: '7DbXNPWlNDR4QYVvFZjr',
    email: 'evan.carlson@example.com',
    firstName: 'Evan',
    lastName: 'Carlson',
    picture: 'https://randomuser.me/api/portraits/men/80.jpg',
    title: 'mr',
  },
  {
    id: '0F8JIqi4zwvb77FGz6Wt',
    email: 'heinz-georg.fiedler@example.com',
    firstName: 'Heinz-Georg',
    lastName: 'Fiedler',
    picture: 'https://randomuser.me/api/portraits/men/81.jpg',
    title: 'mr',
  },
  {
    id: '0P6E1d4nr0L1ntW8cjGU',
    email: 'katie.hughes@example.com',
    firstName: 'Katie',
    lastName: 'Hughes',
    picture: 'https://randomuser.me/api/portraits/women/74.jpg',
    title: 'miss',
  },
  {
    id: '5aZRSdkcBOM6j3lkWEoP',
    email: 'lilja.lampinen@example.com',
    firstName: 'Lilja',
    lastName: 'Lampinen',
    picture: 'https://randomuser.me/api/portraits/women/50.jpg',
    title: 'ms',
  },
  {
    id: '5tVxgsqPCjv2Ul5Rc7gw',
    email: 'abigail.liu@example.com',
    firstName: 'Abigail',
    lastName: 'Liu',
    picture: 'https://randomuser.me/api/portraits/women/83.jpg',
    title: 'miss',
  },
  {
    id: '3JAf8R85oIlxXd58Piqk',
    email: 'joey.oliver@example.com',
    firstName: 'Joey',
    lastName: 'Oliver',
    picture: 'https://randomuser.me/api/portraits/men/61.jpg',
    title: 'mr',
  },
  {
    id: '6wy6UNkZueJfIUfq88d5',
    email: 'melanie.pilz@example.com',
    firstName: 'Melanie',
    lastName: 'Pilz',
    picture: 'https://randomuser.me/api/portraits/women/32.jpg',
    title: 'miss',
  },
  {
    id: '1OuR3CWOEsfISTpFxsG7',
    email: 'dylan.vasquez@example.com',
    firstName: 'Dylan',
    lastName: 'Vasquez',
    picture: 'https://randomuser.me/api/portraits/men/66.jpg',
    title: 'mr',
  },
  {
    id: '1pRsh5nXDIH3pjEOZ17A',
    email: 'margarita.vicente@example.com',
    firstName: 'Margarita',
    lastName: 'Vicente',
    picture: 'https://randomuser.me/api/portraits/women/5.jpg',
    title: 'miss',
  },
];

export const usersSortedByLastNameDesc = [
  {
    id: '1Lkk06cOUCkiAsUXFLMN',
    email: 'vetle.aasland@example.com',
    firstName: 'Vetle',
    lastName: 'Aasland',
    picture: 'https://randomuser.me/api/portraits/men/97.jpg',
    title: 'mr',
  },
  {
    id: '7DbXNPWlNDR4QYVvFZjr',
    email: 'evan.carlson@example.com',
    firstName: 'Evan',
    lastName: 'Carlson',
    picture: 'https://randomuser.me/api/portraits/men/80.jpg',
    title: 'mr',
  },
  {
    id: '0F8JIqi4zwvb77FGz6Wt',
    email: 'heinz-georg.fiedler@example.com',
    firstName: 'Heinz-Georg',
    lastName: 'Fiedler',
    picture: 'https://randomuser.me/api/portraits/men/81.jpg',
    title: 'mr',
  },
  {
    id: '0P6E1d4nr0L1ntW8cjGU',
    email: 'katie.hughes@example.com',
    firstName: 'Katie',
    lastName: 'Hughes',
    picture: 'https://randomuser.me/api/portraits/women/74.jpg',
    title: 'miss',
  },
  {
    id: '5aZRSdkcBOM6j3lkWEoP',
    email: 'lilja.lampinen@example.com',
    firstName: 'Lilja',
    lastName: 'Lampinen',
    picture: 'https://randomuser.me/api/portraits/women/50.jpg',
    title: 'ms',
  },
  {
    id: '5tVxgsqPCjv2Ul5Rc7gw',
    email: 'abigail.liu@example.com',
    firstName: 'Abigail',
    lastName: 'Liu',
    picture: 'https://randomuser.me/api/portraits/women/83.jpg',
    title: 'miss',
  },
  {
    id: '3JAf8R85oIlxXd58Piqk',
    email: 'joey.oliver@example.com',
    firstName: 'Joey',
    lastName: 'Oliver',
    picture: 'https://randomuser.me/api/portraits/men/61.jpg',
    title: 'mr',
  },
  {
    id: '6wy6UNkZueJfIUfq88d5',
    email: 'melanie.pilz@example.com',
    firstName: 'Melanie',
    lastName: 'Pilz',
    picture: 'https://randomuser.me/api/portraits/women/32.jpg',
    title: 'miss',
  },
  {
    id: '1OuR3CWOEsfISTpFxsG7',
    email: 'dylan.vasquez@example.com',
    firstName: 'Dylan',
    lastName: 'Vasquez',
    picture: 'https://randomuser.me/api/portraits/men/66.jpg',
    title: 'mr',
  },
  {
    id: '1pRsh5nXDIH3pjEOZ17A',
    email: 'margarita.vicente@example.com',
    firstName: 'Margarita',
    lastName: 'Vicente',
    picture: 'https://randomuser.me/api/portraits/women/5.jpg',
    title: 'miss',
  },
];
